cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
brew "emacs", args: ["with-cocoa", "with-gnutls"]
brew "ripgrep"
cask "brave-browser"
cask "telegram"
cask "slack"
cask "iterm2"
brew "fish"
cask "jetbrains-toolbox"
brew "git"
brew "tldr"
brew "bat"
brew "fd"
brew "jq"
brew "terminal-notifier"
cask "evernote"
cask "font-meslo-nerd-font-mono"
brew "grc"
cask "flycut"
cask "spotify"
brew "asdf"
# erlang dependencies
brew "autoconf"
brew "wxmac"
brew "openssl"
brew "fop"
# finish - erlang dependencies
cask "visual-studio-code"
brew "tree"
cask "zoomus"
brew "httpie"
cask "docker"
cask "the-unarchiver"
